#[cfg(test)]
mod test {
    use crate::core::{self, event, player, position, style};

    #[test]
    fn play() {
        // home
        let home_squad = core::squad::Squad {
            manager: &core::manager::Manager {
                id: 1,
                team_id: 1,
                country_id: 2, //1  - england, 2 - spain, 3 - germany, 4 - italy,5 - france, 6 - netherlands, 7 - brazil,8 - ukraine, 9 - ghana, 10 - swiss, 11 - norway,12 - portugal, 13 - argentina,14 - denmark,15 - belgium
                name: "Mikel Arteta".to_owned(),
                tactical: 210,
                management: 200,
                coaching: 190,
            },
            subs: vec![],
            tactics: core::tactics::Tactics {
                defense_line: 200,
                compactness: 140,
                aggression: 170,
                build_up_speed: 160,
                attack_width: core::tactics::Width::Balanced,
                shoot_more_often: false,
                cross_more_often: false,
                pass_range: 120,
            },
            players: [
                &player::Player {
                    id: 1,
                    name: "Aaron Ramsdale".to_owned(),
                    team_id: 1,
                    country_id: 1,
                    height: 188,
                    morale: 190,
                    form: 200,
                    tactical: 190,
                    leadership: 150,
                    decision_making: 180,
                    creativity: 110,
                    vision: 130,
                    fitness: 200,
                    pace: 130,
                    strength: 160,
                    stamina: 160,
                    jumping: 170,
                    passing: 170,
                    technique: 90,
                    heading: 90,
                    set_pieces: 50,
                    tackling: 160,
                    marking: 100,
                    goalkeeping: 210,
                    defensive_positioning: 200,
                    shooting: 20,
                    long_shots: 20,
                    attack_positioning: 10,
                    position: position::Position::Goalkeeper,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 2,
                    name: "Ben White".to_owned(),
                    team_id: 1,
                    country_id: 1,
                    height: 182,
                    morale: 195,
                    form: 180,
                    tactical: 190,
                    leadership: 150,
                    decision_making: 190,
                    creativity: 140,
                    vision: 160,
                    fitness: 200,
                    pace: 185,
                    strength: 160,
                    stamina: 180,
                    jumping: 180,
                    passing: 200,
                    technique: 190,
                    heading: 170,
                    set_pieces: 190,
                    tackling: 210,
                    marking: 200,
                    goalkeeping: 10,
                    defensive_positioning: 220,
                    shooting: 150,
                    long_shots: 130,
                    attack_positioning: 150,
                    position: position::Position::RightBack,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 3,
                    name: "William Saliba".to_owned(),
                    team_id: 1,
                    country_id: 5,
                    height: 193,
                    morale: 220,
                    form: 240,
                    tactical: 200,
                    leadership: 170,
                    decision_making: 210,
                    creativity: 110,
                    vision: 120,
                    fitness: 230,
                    pace: 190,
                    strength: 240,
                    stamina: 190,
                    jumping: 200,
                    passing: 160,
                    technique: 140,
                    heading: 230,
                    set_pieces: 50,
                    tackling: 240,
                    marking: 210,
                    goalkeeping: 10,
                    defensive_positioning: 250,
                    shooting: 30,
                    long_shots: 70,
                    attack_positioning: 20,
                    position: position::Position::CenterBack,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 4,
                    name: "Gabriel Magalhaes".to_owned(),
                    team_id: 1,
                    country_id: 7,
                    height: 190,
                    morale: 180,
                    form: 160,
                    tactical: 150,
                    leadership: 170,
                    decision_making: 160,
                    creativity: 90,
                    vision: 110,
                    fitness: 190,
                    pace: 150,
                    strength: 220,
                    stamina: 190,
                    jumping: 200,
                    passing: 140,
                    technique: 120,
                    heading: 220,
                    set_pieces: 50,
                    tackling: 220,
                    marking: 200,
                    goalkeeping: 10,
                    defensive_positioning: 220,
                    shooting: 20,
                    long_shots: 20,
                    attack_positioning: 10,
                    position: position::Position::CenterBack,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 5,
                    name: "Oleksandr Zinchenko".to_owned(),
                    team_id: 1,
                    country_id: 8,
                    height: 175,
                    morale: 200,
                    form: 200,
                    tactical: 210,
                    leadership: 140,
                    decision_making: 200,
                    creativity: 170,
                    vision: 170,
                    fitness: 200,
                    pace: 180,
                    strength: 140,
                    stamina: 190,
                    jumping: 140,
                    passing: 210,
                    technique: 200,
                    heading: 130,
                    set_pieces: 190,
                    tackling: 160,
                    marking: 150,
                    goalkeeping: 10,
                    defensive_positioning: 180,
                    shooting: 140,
                    long_shots: 120,
                    attack_positioning: 180,
                    position: position::Position::LeftBack,
                    playstyle: style::PlayStyle::Inverted,
                },
                &player::Player {
                    id: 6,
                    name: "Sambi Lakonga".to_owned(),
                    team_id: 1,
                    country_id: 15,
                    height: 183,
                    morale: 175,
                    form: 170,
                    tactical: 170,
                    leadership: 140,
                    decision_making: 160,
                    creativity: 130,
                    vision: 170,
                    fitness: 190,
                    pace: 180,
                    strength: 200,
                    stamina: 180,
                    jumping: 170,
                    passing: 190,
                    technique: 170,
                    heading: 160,
                    set_pieces: 130,
                    tackling: 170,
                    marking: 160,
                    goalkeeping: 10,
                    defensive_positioning: 170,
                    shooting: 140,
                    long_shots: 120,
                    attack_positioning: 140,
                    position: position::Position::DefensiveMidfield,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 7,
                    name: "Granit Xhaka".to_owned(),
                    team_id: 1,
                    country_id: 10,
                    height: 186,
                    morale: 230,
                    form: 220,
                    tactical: 210,
                    leadership: 240,
                    decision_making: 200,
                    creativity: 200,
                    vision: 200,
                    fitness: 200,
                    pace: 150,
                    strength: 190,
                    stamina: 190,
                    jumping: 160,
                    passing: 220,
                    technique: 210,
                    heading: 180,
                    set_pieces: 180,
                    tackling: 190,
                    marking: 170,
                    goalkeeping: 10,
                    defensive_positioning: 180,
                    shooting: 130,
                    long_shots: 190,
                    attack_positioning: 190,
                    position: position::Position::DefensiveMidfield,
                    playstyle: style::PlayStyle::BoxToBox,
                },
                &player::Player {
                    id: 8,
                    name: "Emile Smith Rowe".to_owned(),
                    team_id: 1,
                    country_id: 1,
                    height: 182,
                    morale: 210,
                    form: 180,
                    tactical: 200,
                    leadership: 170,
                    decision_making: 200,
                    creativity: 220,
                    vision: 200,
                    fitness: 200,
                    pace: 170,
                    strength: 140,
                    stamina: 180,
                    jumping: 140,
                    passing: 210,
                    technique: 220,
                    heading: 130,
                    set_pieces: 160,
                    tackling: 120,
                    marking: 110,
                    goalkeeping: 10,
                    defensive_positioning: 100,
                    shooting: 130,
                    long_shots: 150,
                    attack_positioning: 200,
                    position: position::Position::AttackingMidfield,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 9,
                    name: "Bukayo Saka".to_owned(),
                    team_id: 1,
                    country_id: 1,
                    height: 178,
                    morale: 180,
                    form: 180,
                    tactical: 200,
                    leadership: 130,
                    decision_making: 230,
                    creativity: 210,
                    vision: 210,
                    fitness: 190,
                    pace: 220,
                    strength: 170,
                    stamina: 190,
                    jumping: 130,
                    passing: 200,
                    technique: 250,
                    heading: 130,
                    set_pieces: 200,
                    tackling: 150,
                    marking: 140,
                    goalkeeping: 10,
                    defensive_positioning: 150,
                    shooting: 200,
                    long_shots: 150,
                    attack_positioning: 240,
                    position: position::Position::RightWing,
                    playstyle: style::PlayStyle::CutInside,
                },
                &player::Player {
                    id: 10,
                    name: "Gabriel Martinelli".to_owned(),
                    team_id: 1,
                    country_id: 8,
                    height: 178,
                    morale: 220,
                    form: 230,
                    tactical: 210,
                    leadership: 140,
                    decision_making: 230,
                    creativity: 220,
                    vision: 200,
                    fitness: 200,
                    pace: 240,
                    strength: 160,
                    stamina: 160,
                    jumping: 180,
                    passing: 200,
                    technique: 250,
                    heading: 150,
                    set_pieces: 170,
                    tackling: 120,
                    marking: 100,
                    goalkeeping: 10,
                    defensive_positioning: 110,
                    shooting: 200,
                    long_shots: 190,
                    attack_positioning: 240,
                    position: position::Position::LeftWing,
                    playstyle: style::PlayStyle::CutInside,
                },
                &player::Player {
                    id: 11,
                    name: "Gabriel Jesus".to_owned(),
                    team_id: 1,
                    country_id: 8,
                    height: 175,
                    morale: 210,
                    form: 230,
                    tactical: 200,
                    leadership: 190,
                    decision_making: 210,
                    creativity: 200,
                    vision: 200,
                    fitness: 200,
                    pace: 220,
                    strength: 180,
                    stamina: 180,
                    jumping: 190,
                    passing: 200,
                    technique: 240,
                    heading: 180,
                    set_pieces: 190,
                    tackling: 130,
                    marking: 100,
                    goalkeeping: 10,
                    defensive_positioning: 100,
                    shooting: 230,
                    long_shots: 210,
                    attack_positioning: 240,
                    position: position::Position::Striker,
                    playstyle: style::PlayStyle::Default,
                },
            ],
        };
        // away
        let away_squad = core::squad::Squad {
            manager: &core::manager::Manager {
                id: 2,
                team_id: 2,
                country_id: 6,
                name: "Erik Ten Haag".to_owned(),
                tactical: 220,
                management: 190,
                coaching: 200,
            },
            subs: vec![],
            tactics: core::tactics::Tactics {
                defense_line: 170,
                compactness: 120,
                aggression: 160,
                build_up_speed: 110,
                attack_width: core::tactics::Width::Balanced,
                shoot_more_often: false,
                cross_more_often: false,
                pass_range: 110,
            },
            players: [
                &player::Player {
                    id: 12,
                    name: "David De Gea".to_owned(),
                    team_id: 2,
                    country_id: 2,
                    height: 192,
                    morale: 200,
                    form: 180,
                    tactical: 170,
                    leadership: 190,
                    decision_making: 190,
                    creativity: 120,
                    vision: 110,
                    fitness: 200,
                    pace: 130,
                    strength: 180,
                    stamina: 180,
                    jumping: 200,
                    passing: 140,
                    technique: 80,
                    heading: 80,
                    set_pieces: 50,
                    tackling: 180,
                    marking: 100,
                    goalkeeping: 220,
                    defensive_positioning: 210,
                    shooting: 20,
                    long_shots: 20,
                    attack_positioning: 10,
                    position: position::Position::Goalkeeper,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 13,
                    name: "Diogo Dalot".to_owned(),
                    team_id: 2,
                    country_id: 12,
                    height: 184,
                    morale: 190,
                    form: 170,
                    tactical: 170,
                    leadership: 130,
                    decision_making: 170,
                    creativity: 150,
                    vision: 130,
                    fitness: 200,
                    pace: 180,
                    strength: 150,
                    stamina: 190,
                    jumping: 140,
                    passing: 180,
                    technique: 170,
                    heading: 80,
                    set_pieces: 110,
                    tackling: 180,
                    marking: 140,
                    goalkeeping: 10,
                    defensive_positioning: 180,
                    shooting: 80,
                    long_shots: 100,
                    attack_positioning: 160,
                    position: position::Position::RightBack,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 14,
                    name: "Lisandro Martinez".to_owned(),
                    team_id: 2,
                    country_id: 13,
                    height: 175,
                    morale: 200,
                    form: 210,
                    tactical: 200,
                    leadership: 200,
                    decision_making: 200,
                    creativity: 130,
                    vision: 120,
                    fitness: 200,
                    pace: 170,
                    strength: 150,
                    stamina: 190,
                    jumping: 170,
                    passing: 160,
                    technique: 180,
                    heading: 170,
                    set_pieces: 140,
                    tackling: 230,
                    marking: 210,
                    goalkeeping: 20,
                    defensive_positioning: 240,
                    shooting: 20,
                    long_shots: 120,
                    attack_positioning: 90,
                    position: position::Position::CenterBack,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 15,
                    name: "Raphael Varane".to_owned(),
                    team_id: 2,
                    country_id: 6,
                    height: 191,
                    morale: 180,
                    form: 170,
                    tactical: 160,
                    leadership: 170,
                    decision_making: 170,
                    creativity: 110,
                    vision: 110,
                    fitness: 200,
                    pace: 190,
                    strength: 210,
                    stamina: 190,
                    jumping: 200,
                    passing: 150,
                    technique: 170,
                    heading: 210,
                    set_pieces: 100,
                    tackling: 210,
                    marking: 210,
                    goalkeeping: 20,
                    defensive_positioning: 210,
                    shooting: 20,
                    long_shots: 90,
                    attack_positioning: 80,
                    position: position::Position::CenterBack,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 16,
                    name: "Tyrell Malacia".to_owned(),
                    team_id: 2,
                    country_id: 6,
                    height: 169,
                    morale: 190,
                    form: 190,
                    tactical: 180,
                    leadership: 150,
                    decision_making: 170,
                    creativity: 140,
                    vision: 130,
                    fitness: 200,
                    pace: 200,
                    strength: 190,
                    stamina: 190,
                    jumping: 140,
                    passing: 170,
                    technique: 180,
                    heading: 130,
                    set_pieces: 140,
                    tackling: 180,
                    marking: 140,
                    goalkeeping: 20,
                    defensive_positioning: 210,
                    shooting: 20,
                    long_shots: 100,
                    attack_positioning: 160,
                    position: position::Position::LeftBack,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 17,
                    name: "Casemiro".to_owned(),
                    team_id: 2,
                    country_id: 7,
                    height: 185,
                    morale: 185,
                    form: 170,
                    tactical: 170,
                    leadership: 180,
                    decision_making: 180,
                    creativity: 160,
                    vision: 140,
                    fitness: 200,
                    pace: 180,
                    strength: 210,
                    stamina: 210,
                    jumping: 190,
                    passing: 190,
                    technique: 180,
                    heading: 180,
                    set_pieces: 150,
                    tackling: 210,
                    marking: 160,
                    goalkeeping: 20,
                    defensive_positioning: 200,
                    shooting: 20,
                    long_shots: 170,
                    attack_positioning: 170,
                    position: position::Position::DefensiveMidfield,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 18,
                    name: "Christian Eriksen".to_owned(),
                    team_id: 2,
                    country_id: 14,
                    height: 182,
                    morale: 190,
                    form: 200,
                    tactical: 200,
                    leadership: 190,
                    decision_making: 200,
                    creativity: 210,
                    vision: 230,
                    fitness: 200,
                    pace: 150,
                    strength: 150,
                    stamina: 170,
                    jumping: 150,
                    passing: 240,
                    technique: 230,
                    heading: 130,
                    set_pieces: 210,
                    tackling: 130,
                    marking: 110,
                    goalkeeping: 20,
                    defensive_positioning: 100,
                    shooting: 140,
                    long_shots: 180,
                    attack_positioning: 180,
                    position: position::Position::CenterMidfield,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 19,
                    name: "Bruno Fernandes".to_owned(),
                    team_id: 2,
                    country_id: 12,
                    height: 179,
                    morale: 190,
                    form: 160,
                    tactical: 180,
                    leadership: 150,
                    decision_making: 180,
                    creativity: 200,
                    vision: 200,
                    fitness: 200,
                    pace: 180,
                    strength: 170,
                    stamina: 180,
                    jumping: 160,
                    passing: 210,
                    technique: 230,
                    heading: 140,
                    set_pieces: 190,
                    tackling: 120,
                    marking: 100,
                    goalkeeping: 20,
                    defensive_positioning: 90,
                    shooting: 140,
                    long_shots: 180,
                    attack_positioning: 200,
                    position: position::Position::AttackingMidfield,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 20,
                    name: "Jadon Sancho".to_owned(),
                    team_id: 2,
                    country_id: 1,
                    height: 180,
                    morale: 200,
                    form: 200,
                    tactical: 160,
                    leadership: 140,
                    decision_making: 180,
                    creativity: 180,
                    vision: 180,
                    fitness: 200,
                    pace: 210,
                    strength: 180,
                    stamina: 180,
                    jumping: 140,
                    passing: 190,
                    technique: 220,
                    heading: 170,
                    set_pieces: 180,
                    tackling: 100,
                    marking: 90,
                    goalkeeping: 20,
                    defensive_positioning: 80,
                    shooting: 190,
                    long_shots: 170,
                    attack_positioning: 210,
                    position: position::Position::RightWing,
                    playstyle: style::PlayStyle::CutInside,
                },
                &player::Player {
                    id: 21,
                    name: "Marcus Rashford".to_owned(),
                    team_id: 2,
                    country_id: 1,
                    height: 180,
                    morale: 200,
                    form: 170,
                    tactical: 160,
                    leadership: 130,
                    decision_making: 140,
                    creativity: 170,
                    vision: 180,
                    fitness: 200,
                    pace: 220,
                    strength: 200,
                    stamina: 190,
                    jumping: 190,
                    passing: 190,
                    technique: 230,
                    heading: 200,
                    set_pieces: 200,
                    tackling: 90,
                    marking: 70,
                    goalkeeping: 20,
                    defensive_positioning: 70,
                    shooting: 180,
                    long_shots: 140,
                    attack_positioning: 220,
                    position: position::Position::Striker,
                    playstyle: style::PlayStyle::Default,
                },
                &player::Player {
                    id: 22,
                    name: "Antony".to_owned(),
                    team_id: 2,
                    country_id: 7,
                    height: 174,
                    morale: 190,
                    form: 200,
                    tactical: 190,
                    leadership: 150,
                    decision_making: 190,
                    creativity: 200,
                    vision: 170,
                    fitness: 200,
                    pace: 220,
                    strength: 170,
                    stamina: 170,
                    jumping: 160,
                    passing: 200,
                    technique: 250,
                    heading: 160,
                    set_pieces: 190,
                    tackling: 70,
                    marking: 30,
                    goalkeeping: 20,
                    defensive_positioning: 60,
                    shooting: 210,
                    long_shots: 180,
                    attack_positioning: 210,
                    position: position::Position::LeftWing,
                    playstyle: style::PlayStyle::CutInside,
                },
            ],
        };

        println!("First leg");
        {
            let mut game = core::game::Game::new(home_squad.clone(), away_squad.clone());
            game.play();
            let home_stats = game.get_home_stats();
            let away_stats = game.get_away_stats();

            println!(
                "Arsenal: {}|Poss:{}|Shots: {}|ShotsOnTarget:{}|Fouls:{}|YellowCards:{}|RedCards:{}|",
                home_stats.goals,
                home_stats.possession * 100.0,
                home_stats.shots,
                home_stats.shots_on_target,
                home_stats.fouls,
                home_stats.yellow_cards.len(),
                home_stats.red_cards.len()
            );
            println!(
                "ManUtd: {}|Poss:{}|Shots: {}|ShotsOnTarget:{}|Fouls:{}|YellowCards:{}|RedCards:{}|",
                away_stats.goals,
                away_stats.possession * 100.0,
                away_stats.shots,
                away_stats.shots_on_target,
                away_stats.fouls,
                away_stats.yellow_cards.len(),
                away_stats.red_cards.len()
            );

            // inspect game details
            {
                for ev in game.get_events() {
                    let (event, min) = ev;
                    match event {
                        event::Event::Goal(scorer_id, _) => {
                            let mut scorer = home_squad.players.iter().find(|p| p.id == scorer_id);
                            if scorer.is_none() {
                                scorer = away_squad.players.iter().find(|p| p.id == scorer_id);
                            }
                            println!("{} '{}", scorer.unwrap().name, min);
                        }
                        _ => {
                            println!("{} '{}", event, min);
                        }
                    }
                }
            }
        }

        println!("Second leg");
        {
            let mut game = core::game::Game::new(away_squad.clone(), home_squad.clone());
            game.play();
            let home_stats = game.get_home_stats();
            let away_stats = game.get_away_stats();

            println!(
                "ManUtd: {}|Poss:{}|Shots: {}|ShotsOnTarget:{}|Fouls:{}|YellowCards:{}|RedCards:{}|",
                home_stats.goals,
                home_stats.possession * 100.0,
                home_stats.shots,
                home_stats.shots_on_target,
                home_stats.fouls,
                home_stats.yellow_cards.len(),
                home_stats.red_cards.len()
            );
            println!(
                "Arsenal: {}|Poss:{}|Shots: {}|ShotsOnTarget:{}|Fouls:{}|YellowCards:{}|RedCards:{}|",
                away_stats.goals,
                away_stats.possession * 100.0,
                away_stats.shots,
                away_stats.shots_on_target,
                away_stats.fouls,
                away_stats.yellow_cards.len(),
                away_stats.red_cards.len()
            );

            // inspect game details
            {
                for ev in game.get_events() {
                    let (event, min) = ev;
                    match event {
                        event::Event::Goal(scorer_id, _) => {
                            let mut scorer = home_squad.players.iter().find(|p| p.id == scorer_id);
                            if scorer.is_none() {
                                scorer = away_squad.players.iter().find(|p| p.id == scorer_id);
                            }
                            println!("{} '{}", scorer.unwrap().name, min);
                        }
                        _ => {
                            println!("{} '{}", event, min);
                        }
                    }
                }
            }
        }
    }
}
