pub enum Position {
    Goalkeeper,
    LeftBack,
    CenterBack,
    RightBack,
    LeftWingBack,
    RightWingBack,
    DefensiveMidfield,
    CenterMidfield,
    AttackingMidfield,
    LeftMidfield,
    RightMidfield,
    LeftWing,
    RightWing,
    Striker,
}
